// Compiles tokens/tokens.json into CSS custom properties, split JSON exports and TypeScript
// types. tailwind.config.ts reads the same JSON, so the outputs cannot drift apart.
import fs from 'fs';
import path from 'path';

const root = path.resolve(__dirname, '..');
const tokens = JSON.parse(fs.readFileSync(path.join(root, 'tokens/tokens.json'), 'utf-8'));

type Leaf = { value: string; description?: string };
const isLeaf = (v: unknown): v is Leaf => !!v && typeof v === 'object' && 'value' in (v as object);

function flatten(obj: Record<string, unknown>, prefix: string[] = []): [string[], Leaf][] {
  return Object.entries(obj).flatMap(([key, val]) =>
    isLeaf(val) ? [[[...prefix, key], val] as [string[], Leaf]] : flatten(val as Record<string, unknown>, [...prefix, key])
  );
}

// {color.semantic.neutral.900} -> var(--semantic-neutral-900)
function resolveRef(value: string): string {
  return value.replace(/\{color\.([^}]+)\}/g, (_, ref: string) => `var(--${ref.split('.').join('-')})`);
}

for (const group of ['color', 'typography', 'spatial', 'motion'] as const) {
  fs.writeFileSync(path.join(root, `tokens/${group}.json`), JSON.stringify(tokens[group], null, 2) + '\n');
}

const css: string[] = [
  '/* AUTO-GENERATED by scripts/build-tokens.ts from tokens/tokens.json — do not edit by hand. */',
  ':root {',
];
const colorNames: string[] = [];

css.push('  /* Color primitives */');
for (const [keys, leaf] of flatten(tokens.color.brand, ['brand']).concat(flatten(tokens.color.semantic, ['semantic']))) {
  css.push(`  --${keys.join('-')}: ${leaf.value};`);
  colorNames.push(keys.join('-'));
}
css.push('  /* Semantic aliases (reference primitives) */');
for (const [keys, leaf] of flatten(tokens.color.alias)) {
  css.push(`  --${keys.join('-')}: ${resolveRef(leaf.value)};`);
  colorNames.push(keys.join('-'));
}

css.push('  /* Typography */');
css.push(`  --font-sans: ${tokens.typography.fontFamily.sans.value};`);
css.push(`  --font-mono: ${tokens.typography.fontFamily.mono.value};`);
for (const [name, def] of Object.entries<any>(tokens.typography.scale)) {
  css.push(`  --font-size-${name}: ${def.fontSize.value};`);
  css.push(`  --line-height-${name}: ${def.lineHeight.value};`);
  css.push(`  --font-weight-${name}: ${def.fontWeight.value};`);
  css.push(`  --letter-spacing-${name}: ${def.letterSpacing.value};`);
}
for (const [name, def] of Object.entries<any>(tokens.typography.dynamicMatrix)) {
  css.push(`  --dynamic-type-${name}-size: ${def.fontSize.value};`);
  css.push(`  --dynamic-type-${name}-lh: ${def.lineHeight.value};`);
}

css.push('  /* Spatial */');
css.push(`  --grid-base: ${tokens.spatial.gridBase.value};`);
for (const [k, v] of Object.entries<any>(tokens.spatial.spacing)) css.push(`  --space-${k}: ${v.value};`);
for (const [k, v] of Object.entries<any>(tokens.spatial.radius)) css.push(`  --radius-${k}: ${v.value};`);
for (const [k, v] of Object.entries<any>(tokens.spatial.elevation)) css.push(`  --elevation-${k}: ${v.value};`);
css.push(`  --button-padding-x: ${tokens.spatial.button.paddingHorizontal.value};`);
css.push(`  --button-padding-y: ${tokens.spatial.button.paddingVertical.value};`);
css.push(`  --button-height: ${tokens.spatial.button.height.value};`);
css.push(`  --button-radius: ${tokens.spatial.button.radius.value};`);
css.push(`  --touch-target-min: ${tokens.spatial.touchTargetMin.value};`);

css.push('  /* Motion */');
for (const [k, v] of Object.entries<any>(tokens.motion.duration)) css.push(`  --duration-${k}: ${v.value};`);
for (const [k, v] of Object.entries<any>(tokens.motion.easing)) css.push(`  --easing-${k}: ${v.value};`);
css.push('}', '');

fs.mkdirSync(path.join(root, 'styles'), { recursive: true });
fs.writeFileSync(path.join(root, 'styles/tokens.css'), css.join('\n'));

const union = (names: string[]) => names.map((n) => `  | '${n}'`).join('\n');
const types = `/* AUTO-GENERATED by scripts/build-tokens.ts from tokens/tokens.json — do not edit by hand. */
export interface TokenDef {
  value: string;
  description?: string;
}

export type ColorTokenName =
${union(colorNames)};

export type TypeScaleName =
${union(Object.keys(tokens.typography.scale))};

export type SpacingTokenName =
${union(Object.keys(tokens.spatial.spacing))};

export type RadiusTokenName =
${union(Object.keys(tokens.spatial.radius))};

export type ElevationTokenName =
${union(Object.keys(tokens.spatial.elevation))};
`;
fs.mkdirSync(path.join(root, 'types'), { recursive: true });
fs.writeFileSync(path.join(root, 'types/tokens.ts'), types);

console.log(`✓ Compiled ${colorNames.length} color tokens, ${Object.keys(tokens.typography.scale).length} type styles → styles/tokens.css, types/tokens.ts`);
